#!/usr/bin/env -S node --enable-source-maps

import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { encode } from 'cbor2';
import { parseEDN } from 'cbor-edn';

// Get input and output file paths from command line arguments
const [,, inputFile, outputFile] = process.argv;

if (!inputFile || !outputFile) {
    console.error('Usage: node edn2cbor <inputFile> <outputFile>');
    process.exit(1);
}

// Convert paths
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const inputPath = path.resolve(__dirname, inputFile);
const outputPath = path.resolve(__dirname, outputFile);

try {
    // Read EDN file
    const ednData = await readFile(inputPath, 'utf-8');
    
    // Parse EDN and convert to CBOR
    const parsedEdn = parseEDN(ednData);
    // if for some reason you need double CBOR encoding
    //const cborData = encode(parsedEdn);
    
    // Write to another file in CBOR format
    await writeFile(outputPath, parsedEdn);
} catch (err) {
    console.error('Error:', err.message);
    process.exit(1);
}
